/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/LR9FOdp4sCW
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"

export function testimonial_card() {
  return (
    <Card className="w-full max-w-md p-6 grid gap-6">
      <div className="flex items-center gap-4">
        <Avatar className="w-14 h-14">
          <AvatarImage src="/placeholder-user.jpg" alt="Testimonial Author" />
          <AvatarFallback>JD</AvatarFallback>
        </Avatar>
        <div className="grid gap-1">
          <div className="font-semibold">John Doe</div>
          <div className="text-sm text-muted-foreground">CEO, Acme Inc.</div>
        </div>
      </div>
      <blockquote className="text-muted-foreground">
        "The team at Vercel has been an absolute pleasure to work with. Their\n platform has allowed us to rapidly
        iterate and deploy our web\n application with ease."
      </blockquote>
      <div className="text-sm text-muted-foreground">
        <time dateTime="2024-08-04">August 4, 2024</time>
      </div>
    </Card>
  )
}
